# Generated by Django 3.1.1 on 2020-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_age_que'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_nr',
        ),
        migrations.AddField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
