# Generated by Django 3.1.1 on 2020-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20201012_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='sex'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intrest',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sex'),
        ),
    ]
