# Generated by Django 3.1.1 on 2020-10-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20201021_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=200)),
                ('to_user', models.CharField(max_length=200)),
            ],
        ),
    ]
